version: "3"
services:
  text-generation-webui-docker:
    build:
      context: .
      target: default  # Specify the variant to build
      args:
        - VERSION_TAG="v1.5"  # Checkout this specific tag from upstream. Omit or set `nightly` for latest.
#        - BUILD_DATE="1970-01-01"  # Set the build date as desired
#        - LCL_SRC_DIR=text-generation-webui  # Developers - see Dockerfile app_base
    container_name: text-generation-webui
    environment:
      - EXTRA_LAUNCH_ARGS="--listen --verbose" # Custom launch args (e.g., --model MODEL_NAME)
#      - BUILD_EXTENSIONS_LIVE="silero_tts whisper_stt" # Install named extensions during every container launch. THIS WILL SIGNIFICANLTLY SLOW LAUNCH TIME.
    ports:
      - 7860:7860  # Default web port
      - 5000:5000  # Default API port
#      - 5005:5005  # Default streaming port
#      - 5001:5001  # Default OpenAI API extension port
    volumes:
      - ./config/characters:/workspace/characters
      - ./config/loras:/workspace/loras
      - ./config/models:/workspace/models
      - ./config/presets:/workspace/presets
      - ./config/prompts:/workspace/prompts
      - ./config/training:/workspace/training
#      - ./config/extensions:/app/extensions  # Persist all extensions
#      - ./config/extensions/silero_tts:/app/extensions/silero_tts  # Persist a single extension
    logging:
      driver:  json-file
      options:
        max-file: "3"   # number of files or file count
        max-size: '10m'
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]
